---
editor_options: 
  markdown: 
    wrap: 72
---

------------------------------------------------------------------------

title: "Business Intelligence Lab Submission Markdown" author: "Acers
Team" date: "11/10/2023"

output: github_document: toc: yes toc_depth: 4 fig_width: 6 fig_height:
4 df_print: default editor_options: chunk_output_type: console ---

# Student Details

+-----------------------+----------------------------------------------+
| **Student ID Numbers  | *\<list one student name, group, and ID per  |
| and Names of Group    | line; you should be between 2 and 5 members  |
| Members**             | per group\>*                                 |
|                       |                                              |
|                       | 1.  122790 - C - Bwalley Nicholas            |
|                       |                                              |
|                       | 2.  133834 - C - Mongare Sarah               |
|                       |                                              |
|                       | 3.  133928 - C - Cheptoi Millicent           |
|                       |                                              |
|                       | 4.  134879 - C - Tulienge Lesley             |
|                       |                                              |
|                       | 5.  124461 - C - Kinya Angela                |
+-----------------------+----------------------------------------------+
| **GitHub Classroom    | Acers Team                                   |
| Group Name**          |                                              |
+-----------------------+----------------------------------------------+
| **Course Code**       | BBT4206                                      |
+-----------------------+----------------------------------------------+
| **Course Name**       | Business Intelligence II                     |
+-----------------------+----------------------------------------------+
| **Program**           | Bachelor of Business Information Technology  |
+-----------------------+----------------------------------------------+
| **Semester Duration** | 21^st^ August 2023 to 28^th^ November 2023   |
+-----------------------+----------------------------------------------+

# Understanding the Dataset (Exploratory Data Analysis (EDA))

## Loading the Dataset

### Source:

The dataset that was used can be downloaded here: *\<provide a link\>*

### Reference:

*\<Cite the dataset here using APA\>\
Refer to the APA 7th edition manual for rules on how to cite datasets:
<https://apastyle.apa.org/style-grammar-guidelines/references/examples/data-set-references>*

## STEP 1. Install and Load the Required Packages ----

```{r code chunk one}
if (require("languageserver")) {
  require("languageserver")
} else {
  install.packages("languageserver", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}


knitr::opts_chunk$set(echo = TRUE, warning = FALSE, eval = TRUE,
                      collapse = FALSE, tidy = TRUE, include=TRUE)
```

**Note:** the following "*R Markdown*" options have been set as the
defaults:

> output:\
> \
> github_document:\
> toc: yes\
> toc_depth: 4\
> fig_width: 6\
> fig_height: 4\
> df_print: default\
> \
> editor_options:\
> chunk_output_type: console

# STEP 1 : Install and load all the packages

We installed all the packages that will enable us execute this lab:

```{r chuck code one}

## mlbench ----
if (require("mlbench")) {
  require("mlbench")
} else {
  install.packages("mlbench", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## readr ----
if (require("readr")) {
  require("readr")
} else {
  install.packages("readr", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## caret ----
if (require("caret")) {
  require("caret")
} else {
  install.packages("caret", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## e1071 ----
if (require("e1071")) {
  require("e1071")
} else {
  install.packages("e1071", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## factoextra ----
if (require("factoextra")) {
  require("factoextra")
} else {
  install.packages("factoextra", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}

## FactoMineR ----
if (require("FactoMineR")) {
  require("FactoMineR")
} else {
  install.packages("FactoMineR", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}
```

## STEP 2: Loading datasets

```{r Dataset Loader}
library(readr)


StudentPerformanceDataset <- read_csv("C:/Users/NICK BWALLEY/OneDrive - Strathmore University/MyStrath/BBIT/4.2/Business Intelligence II - Dr. Allan Omondi/BI2-Labs/BBT4206-R-Lab4of15-DataTransforms-acers_team/data/StudentPerformanceDataset.csv")


View(StudentPerformanceDataset)

```

## STEP 3. Apply a Scale Data Transform ----

```{r code chunk three}
summary(StudentPerformanceDataset)
# The code below converts column number 4 into unlisted and numeric data first
# so that a histogram can be plotted. Further reading:
StudentPerformanceDataset_yield <- as.numeric(unlist(StudentPerformanceDataset[, 4]))
hist(StudentPerformanceDataset_yield, main = names(StudentPerformanceDataset)[4])

model_of_the_transform <- preProcess(StudentPerformanceDataset, method = c("scale"))
print(model_of_the_transform)
student_dataset_scale_transform <- predict(model_of_the_transform, StudentPerformanceDataset)

# AFTER
summary(student_dataset_scale_transform)
student_datasetset_yield <- as.numeric(unlist(student_dataset_scale_transform[, 4]))
hist(student_datasetset_yield, main = names(student_dataset_scale_transform)[4])
```

## STEP 4. Apply a Centre Data Transform ----

```{r code chunk four}
### The Centre Basic Transform on the StudentDataset ----
summary(StudentPerformanceDataset)
model_of_the_transform <- preProcess(StudentPerformanceDataset, method = c("center"))
print(model_of_the_transform)
student_dataset_center_transform <- predict(model_of_the_transform, StudentPerformanceDataset)
summary(student_dataset_center_transform)

### The Standardize Basic Transform on the Student Dataset ----
# BEFORE
summary(StudentPerformanceDataset)
sapply(StudentPerformanceDataset[, 4], sd)
model_of_the_transform <- preProcess(StudentPerformanceDataset,
                                     method = c("scale", "center"))
print(model_of_the_transform)
student_dataset_standardize_transform <- predict(model_of_the_transform, StudentPerformanceDataset) # nolint

# AFTER
summary(student_dataset_standardize_transform)
sapply(student_dataset_standardize_transform[, 4], sd)
```

## STEP 5. Apply a Standardize Data Transform ----

```{r code chunk five}
### The Standardize Basic Transform on the StudentDataset ----
# BEFORE
summary(StudentPerformanceDataset)
sapply(StudentPerformanceDataset[, 4], sd)
model_of_the_transform <- preProcess(StudentPerformanceDataset,
                                     method = c("scale", "center"))
print(model_of_the_transform)
student_dataset_standardize_transform <- predict(model_of_the_transform, StudentPerformanceDataset) # nolint

# AFTER
summary(student_dataset_standardize_transform)
sapply(student_dataset_standardize_transform[, 4], sd)
```

## STEP 6. Apply a Normalize Data Transform ----

```{code chunk six}
### The Normalize Transform on the StudentDataset ----
summary(StudentPerformanceDataset)
model_of_the_transform <- preProcess(StudentPerformanceDataset, method = c("range"))
print(model_of_the_transform)
student_dataset_normalize_transform <- predict(model_of_the_transform, StudentPerformanceDataset)
summary(student_dataset_normalize_transform)
```

## STEP 7. Apply a Box-Cox Power Transform ----

```{r code chunk seven}
### Box-Cox Power Transform on the StudentDataset ----
# BEFORE
summary(student_dataset_standardize_transform)

# Calculate the skewness before the Box-Cox transform
sapply(student_dataset_standardize_transform[, 4],  skewness, type = 2)
sapply(student_dataset_standardize_transform[, 4], sd)

model_of_the_transform <- preProcess(student_dataset_standardize_transform,
                                     method = c("BoxCox"))
print(model_of_the_transform)
student_dataset_box_cox_transform <- predict(model_of_the_transform,
                                             student_dataset_standardize_transform)

# AFTER
summary(student_dataset_box_cox_transform)

sapply(student_dataset_box_cox_transform[, 4],  skewness, type = 2)
sapply(student_dataset_box_cox_transform[, 4], sd)

# Calculate the skewness after the Box-Cox transform
sapply(student_dataset_box_cox_transform[, 4],  skewness, type = 2)
sapply(student_dataset_box_cox_transform[, 4], sd)
```

## STEP 8. Apply a Yeo-Johnson Power Transform ----

```{r code chunk eight}
### Yeo-Johnson Power Transform on the StudentDataset ----
# BEFORE
summary(student_dataset_standardize_transform)

# Calculate the skewness before the Yeo-Johnson transform
sapply(student_dataset_standardize_transform[, 4],  skewness, type = 2)
sapply(student_dataset_standardize_transform[, 4], sd)

model_of_the_transform <- preProcess(student_dataset_standardize_transform,
                                     method = c("YeoJohnson"))
print(model_of_the_transform)
student_dataset_yeo_johnson_transform <- predict(model_of_the_transform, # nolint
                                                 student_dataset_standardize_transform)

# AFTER
summary(student_dataset_yeo_johnson_transform)

# Calculate the skewness after the Yeo-Johnson transform
sapply(student_dataset_yeo_johnson_transform[, 4],  skewness, type = 2)
sapply(student_dataset_yeo_johnson_transform[, 4], sd)
```

## STEP 9.a. PCA Linear Algebra Transform for Dimensionality Reduction ----

### PCA for Dimensionality Reduction on the Student Dataset ----

Notice that PCA is not applied to the "Student Data" dataset because it
requires multiple numeric independent variables. The dataset has 3
categorical independent variables and only 1 numeric independent
variable.

##STEP 10. ICA Linear Algebra Transform for Dimensionality Reduction
----

```{r code chunk ten}
# Independent Component Analysis (ICA) Linear Algebra Transform ----

# Independent Component Analysis (ICA) transforms the data to return only the
# independent components. The n.comp argument is required to specify the
# desired number of independent components. This also results in a list of
# attributes that are uncorrelated.

if (!is.element("fastICA", installed.packages()[, 1])) {
  install.packages("fastICA", dependencies = TRUE)
}
require("fastICA")

### ICA for Dimensionality Reduction on the Student Dataset ----
# Notice that ICA is not applied to the “Student Data” dataset because it requires
# multiple numeric independent variables. The dataset has 3 categorical
# independent variables and only 1 numeric independent variable.

### ICA for Dimensionality Reduction on the Iris Dataset ----
summary(StudentPerformanceDataset)
model_of_the_transform <- preProcess(StudentPerformanceDataset,
                                     method = c("scale", "center", "ica"),
                                     n.comp = 3)
print(model_of_the_transform)
StudentPerformanceDataset_ica_dr <- predict(model_of_the_transform, StudentPerformanceDataset)

summary(StudentPerformanceDataset_ica_dr)
```
